### ISSUE TITLE
src/raft/raft_time.go   function Wait() : sleep time is not accurate.

### ISSUE THREAD

**Issue by eddiearc** [Anarion-zuo/MIT-6.824-arch#1]
code line 19 Precision Loss question: int divde int will get a int, which add all divDuration will not equal rt.WaitDuration in some case..

**Comment by Anarion-zuo** [comment]
It is intended to be not accurate

**Comment by eddieVim** [comment]
Althrough it accurate, it can't make time random.

**Comment by eddiearc** [comment]
Althrough it not accurate, it can't make time random.

**Comment by Anarion-zuo** [comment]
It is intended to wait for `roughly` the given time. This is not an issue worth noting.
